// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUhGTCmX8nCYs2ervh8KllcdYJtTjAYe0',
    appId: '1:557769794151:web:b334ef721908df7d32aac2',
    messagingSenderId: '557769794151',
    projectId: 'mobo-dragon',
    authDomain: 'mobo-dragon.firebaseapp.com',
    storageBucket: 'mobo-dragon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnblr5yJIbT3veGNdK5olPId2VhOXQpKE',
    appId: '1:557769794151:android:ebe7113c8695267b32aac2',
    messagingSenderId: '557769794151',
    projectId: 'mobo-dragon',
    storageBucket: 'mobo-dragon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtdSrmUBJ3NSHPUs6ztkxtaYb5a232rRQ',
    appId: '1:557769794151:ios:cd4f1a8d3c5d0d9d32aac2',
    messagingSenderId: '557769794151',
    projectId: 'mobo-dragon',
    storageBucket: 'mobo-dragon.appspot.com',
    iosClientId: '557769794151-5csbk2igc6fr5idppklkadj4sknfetf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtdSrmUBJ3NSHPUs6ztkxtaYb5a232rRQ',
    appId: '1:557769794151:ios:cd4f1a8d3c5d0d9d32aac2',
    messagingSenderId: '557769794151',
    projectId: 'mobo-dragon',
    storageBucket: 'mobo-dragon.appspot.com',
    iosClientId: '557769794151-5csbk2igc6fr5idppklkadj4sknfetf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotificationFirebase',
  );
}
